# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HCKalmanFilter Sample' do
    
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    
    pod 'ActionSheetPicker-3.0', '~> 2.5.0'

    pod 'Surge', '~> 2.3'
    
    source 'https://github.com/CocoaPods/Specs.git'
    use_frameworks!
end

