target “HCKalmanFilter” do

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    
    pod 'ActionSheetPicker-3.0', '~> 2.2.0'
      
    source 'https://github.com/CocoaPods/Specs.git'
    use_frameworks!
end
